Fixed script
fmasa/docker-machine-unison pull request #4
Opened 2017-04-05 08:53 UTC by luckydonald

Docker commands changed a little since back-at-the-days.

Should fix #3, too.

2017-04-12 21:36 UTC, fmasa requested changes

2017-04-12 21:36 UTC, fmasa commented on provision.sh
> -startUnison
Please remove `startUnison` definition as well.

2017-05-25 15:57 UTC, fmasa commented on provision.sh
> -startUnison
ping @luckydonald

2018-01-25 11:45 UTC, fmasa commented
ping @luckydonald

2018-01-27 11:58 UTC, luckydonald commented
Why is that needed?

2018-01-27 12:12 UTC, fmasa commented
You replaced `startUnison` function call with `"$INSTALLATION_FOLDER/bin/unison" $UNISON_PROFILE_NAME`, so `startUnison` function is no longer used. So it's useless to leave its declaration there

2018-02-01 14:08 UTC, luckydonald commented
@fmasa Edited with github's online editor, not sure if that messes something up though.

2018-02-03 13:42 UTC, fmasa commented
Thanks :+1:

2018-02-03 13:42 UTC, merged